# NumPy Operations

This notebook demonstrates NumPy array operations, indexing and slicing, reshaping, stacking, broadcasting, matrix multiplication, and solving systems of linear equations.


## Part A: NumPy Operations

### 1. An array from 1 to 20, incremented by 3

In [2]:
import numpy as np

array1 = np.arange(1, 21, 3)
print(array1)


[ 1  4  7 10 13 16 19]


### 2. An array of 3 random numbers between 0 and 1

In [4]:
random_array = np.random.rand(3)
print(random_array)


[0.82705686 0.82227372 0.3352517 ]


### 3. A 2-D array

In [5]:
array2d = np.array([
    [10, 20, 45],
    [30, 12, 16],
    [42, 17, 56]
])

print("Original array:")
print(array2d)

print("\nFirst two rows:")
print(array2d[:2])

print("\nLast two rows:")
print(array2d[-2:])


Original array:
[[10 20 45]
 [30 12 16]
 [42 17 56]]

First two rows:
[[10 20 45]
 [30 12 16]]

Last two rows:
[[30 12 16]
 [42 17 56]]


### 4. A two 2×2 arrays

In [6]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("A:")
print(A)

print("\nB:")
print(B)

print("\nVertical stack:")
print(np.vstack((A, B)))

print("\nHorizontal stack:")
print(np.hstack((A, B)))

print("\nSplit the vertically stacked array:")
print(np.vsplit(np.vstack((A, B)), 2))


A:
[[1 2]
 [3 4]]

B:
[[5 6]
 [7 8]]

Vertical stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stack:
[[1 2 5 6]
 [3 4 7 8]]

Split the vertically stacked array:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


### 5. Matrix multiplication

In [7]:
X = np.array([
    [5, 7, 2],
    [4, 5, 6],
    [7, 4, 2]
])

Y = np.array([
    [4, 2],
    [6, 2],
    [4, 2]
])

print("X shape:", X.shape)
print("Y shape:", Y.shape)

# X is 3x3 and Y is 3x2.
# The inner dimensions are both 3, so X @ Y is possible.

XY = X @ Y
print("\nX @ Y:")
print(XY)

# Y @ X is not possible because the inner dimensions are 2 and 3.
print("\nY @ X is not possible because the dimensions are (3,2) and (3,3).")


X shape: (3, 3)
Y shape: (3, 2)

X @ Y:
[[70 28]
 [70 30]
 [60 26]]

Y @ X is not possible because the dimensions are (3,2) and (3,3).


### 6. Shape and dimensions of vectors

In [8]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print("Shape of x:", x.shape)
print("Number of dimensions of x:", x.ndim)

x_matrix = x.reshape(3, 1)
y_matrix = y.reshape(3, 1)

print("\nx reshaped to (3, 1):")
print(x_matrix)

print("\ny reshaped to (3, 1):")
print(y_matrix)

print("\nNumber of dimensions of y after reshaping:", y_matrix.ndim)


Shape of x: (3,)
Number of dimensions of x: 1

x reshaped to (3, 1):
[[ 2]
 [-1]
 [-8]]

y reshaped to (3, 1):
[[ 3]
 [ 1]
 [-2]]

Number of dimensions of y after reshaping: 2


### 7. Broadcasting Demonstration


In [9]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

values = np.array([1, 2, 3])

print("Matrix:")
print(matrix)

print("\nValues:")
print(values)

print("\nSubtraction:")
print(matrix - values)

print("\nMultiplication:")
print(matrix * values)


Matrix:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Values:
[1 2 3]

Subtraction:
[[ 9 18 27]
 [39 48 57]
 [69 78 87]]

Multiplication:
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


## Part B: Systems of Linear Equations

### 1. System1

In [11]:
A1 = np.array([[2, 3, -4], [1, -4, 0]], dtype=float)
b1 = np.array([6, 8], dtype=float)

print("Coefficient matrix A:")
print(A1)
print("\nConstants vector b:")
print(b1)


Coefficient matrix A:
[[ 2.  3. -4.]
 [ 1. -4.  0.]]

Constants vector b:
[6. 8.]


In [12]:
# Let x3 be the free variable.
x3 = 0

x2 = (4 * x3 - 10) / 11
x1 = (48 + 16 * x3) / 11

print("For x3 =", x3)
print("x1 =", x1)
print("x2 =", x2)
print("x3 =", x3)


For x3 = 0
x1 = 4.363636363636363
x2 = -0.9090909090909091
x3 = 0


#### The number of solutions for system1 using NumPy functions

In [13]:
rank_A1 = np.linalg.matrix_rank(A1)
rank_aug1 = np.linalg.matrix_rank(np.column_stack((A1, b1)))

print("Rank of coefficient matrix:", rank_A1)
print("Rank of augmented matrix:", rank_aug1)

if rank_A1 != rank_aug1:
    print("The system has no solution.")
elif rank_A1 == A1.shape[1]:
    print("The system has one unique solution.")
else:
    print("The system has infinitely many solutions.")


Rank of coefficient matrix: 2
Rank of augmented matrix: 2
The system has infinitely many solutions.


### 2. System2

In [14]:
A2 = np.array([[3, -4, 5], [-1, 2, -4]], dtype=float)
b2 = np.array([10, 8], dtype=float)

print("Coefficient matrix A:")
print(A2)
print("\nConstants vector b:")
print(b2)


Coefficient matrix A:
[[ 3. -4.  5.]
 [-1.  2. -4.]]

Constants vector b:
[10.  8.]


In [15]:
# Let y3 be the free variable.
y3 = 0

y2 = 3 * y3 + 17
y1 = 2 * y3 + 26

print("For y3 =", y3)
print("y1 =", y1)
print("y2 =", y2)
print("y3 =", y3)


For y3 = 0
y1 = 26
y2 = 17
y3 = 0


#### The number of solutions for system2 using NumPy functions


In [16]:
rank_A2 = np.linalg.matrix_rank(A2)
rank_aug2 = np.linalg.matrix_rank(np.column_stack((A2, b2)))

print("Rank of coefficient matrix:", rank_A2)
print("Rank of augmented matrix:", rank_aug2)

if rank_A2 != rank_aug2:
    print("The system has no solution.")
elif rank_A2 == A2.shape[1]:
    print("The system has one unique solution.")
else:
    print("The system has infinitely many solutions.")


Rank of coefficient matrix: 2
Rank of augmented matrix: 2
The system has infinitely many solutions.
